// Prints the coverage totals as a markdown table for GitHub Actions
// Requires `coverage/coverage-summary.json` to exist, which is generated by `vitest --coverage`.

import { readFileSync } from 'node:fs';

const summary = JSON.parse(readFileSync('coverage/coverage-summary.json', 'utf8'));
const total = summary.total;

const row = (label, metric) => `| ${label} | ${metric.pct}% |`;

const table = [
  '## Coverage',
  '',
  '| Metric | Covered |',
  '| --- | --- |',
  row('Statements', total.statements),
  row('Branches', total.branches),
  row('Functions', total.functions),
  row('Lines', total.lines),
].join('\n');

console.log(table);
